name: Rust CI

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust-ci.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        
      - name: Run tests
        run: cargo test --verbose

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        
      - name: Check
        run: cargo check --all-features
        
      - name: Rustfmt
        run: cargo fmt --check
        
      - name: Clippy
        run: cargo clippy